# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fault.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66\x61ult.proto\x12\x06\x61rchie\"\xb7\x01\n\x05\x46\x61ult\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\x04\x12\x0c\n\x04type\x18\x02 \x01(\x04\x12\r\n\x05model\x18\x03 \x01(\x04\x12\x10\n\x08lifespan\x18\x04 \x01(\x04\x12\x17\n\x0ftrigger_address\x18\x05 \x01(\x04\x12\x1a\n\x12trigger_hitcounter\x18\x06 \x01(\x04\x12\x12\n\nmask_upper\x18\x07 \x01(\x04\x12\x12\n\nmask_lower\x18\x08 \x01(\x04\x12\x11\n\tnum_bytes\x18\t \x01(\r\"+\n\nFault_Pack\x12\x1d\n\x06\x66\x61ults\x18\x01 \x03(\x0b\x32\r.archie.Faultb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fault_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FAULT._serialized_start=24
  _FAULT._serialized_end=207
  _FAULT_PACK._serialized_start=209
  _FAULT_PACK._serialized_end=252
# @@protoc_insertion_point(module_scope)
