# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data.proto
# Protobuf Python Version: 6.30.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    1,
    '',
    'data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\x12\x06\x61rchie\"\xf5\x02\n\x04\x44\x61ta\x12\x14\n\x0c\x61rchitecture\x18\x01 \x01(\t\x12\x11\n\tend_point\x18\x02 \x01(\x05\x12\x12\n\nend_reason\x18\x03 \x01(\t\x12.\n\x0ftb_informations\x18\x04 \x03(\x0b\x32\x15.archie.TbInformation\x12+\n\x0etb_exec_orders\x18\x05 \x03(\x0b\x32\x13.archie.TbExecOrder\x12\"\n\tmem_infos\x18\x06 \x03(\x0b\x32\x0f.archie.MemInfo\x12+\n\rregister_info\x18\x07 \x01(\x0b\x32\x14.archie.RegisterInfo\x12*\n\rfaulted_datas\x18\x08 \x03(\x0b\x32\x13.archie.FaultedData\x12+\n\x0emem_dump_infos\x18\t \x03(\x0b\x32\x13.archie.MemDumpInfo\x12)\n\rmem_map_infos\x18\n \x03(\x0b\x32\x12.archie.MemMapInfo\"v\n\rTbInformation\x12\x14\n\x0c\x62\x61se_address\x18\x01 \x01(\x04\x12\x0c\n\x04size\x18\x02 \x01(\x04\x12\x19\n\x11instruction_count\x18\x03 \x01(\x04\x12\x13\n\x0bnum_of_exec\x18\x04 \x01(\x04\x12\x11\n\tassembler\x18\x05 \x01(\t\"3\n\x0bTbExecOrder\x12\x17\n\x0ftb_base_address\x18\x01 \x01(\x04\x12\x0b\n\x03pos\x18\x02 \x01(\x04\"i\n\x07MemInfo\x12\x13\n\x0bins_address\x18\x01 \x01(\x04\x12\x0c\n\x04size\x18\x02 \x01(\x04\x12\x17\n\x0fmemmory_address\x18\x03 \x01(\x04\x12\x11\n\tdirection\x18\x04 \x01(\r\x12\x0f\n\x07\x63ounter\x18\x05 \x01(\x04\"K\n\x0bMemDumpInfo\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\x04\x12\x0b\n\x03len\x18\x02 \x01(\x04\x12\x1e\n\x05\x64umps\x18\x03 \x03(\x0b\x32\x0f.archie.MemDump\"\x16\n\x07MemDump\x12\x0b\n\x03mem\x18\x01 \x01(\x0c\"O\n\x0cRegisterInfo\x12,\n\x0eregister_dumps\x18\x01 \x03(\x0b\x32\x14.archie.RegisterDump\x12\x11\n\tarch_type\x18\x02 \x01(\r\"E\n\x0cRegisterDump\x12\x17\n\x0fregister_values\x18\x01 \x03(\x04\x12\n\n\x02pc\x18\x02 \x01(\x04\x12\x10\n\x08tb_count\x18\x03 \x01(\x04\"9\n\x0b\x46\x61ultedData\x12\x17\n\x0ftrigger_address\x18\x01 \x01(\x04\x12\x11\n\tassembler\x18\x02 \x01(\t\"+\n\nMemMapInfo\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\x04\x12\x0c\n\x04size\x18\x02 \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATA']._serialized_start=23
  _globals['_DATA']._serialized_end=396
  _globals['_TBINFORMATION']._serialized_start=398
  _globals['_TBINFORMATION']._serialized_end=516
  _globals['_TBEXECORDER']._serialized_start=518
  _globals['_TBEXECORDER']._serialized_end=569
  _globals['_MEMINFO']._serialized_start=571
  _globals['_MEMINFO']._serialized_end=676
  _globals['_MEMDUMPINFO']._serialized_start=678
  _globals['_MEMDUMPINFO']._serialized_end=753
  _globals['_MEMDUMP']._serialized_start=755
  _globals['_MEMDUMP']._serialized_end=777
  _globals['_REGISTERINFO']._serialized_start=779
  _globals['_REGISTERINFO']._serialized_end=858
  _globals['_REGISTERDUMP']._serialized_start=860
  _globals['_REGISTERDUMP']._serialized_end=929
  _globals['_FAULTEDDATA']._serialized_start=931
  _globals['_FAULTEDDATA']._serialized_end=988
  _globals['_MEMMAPINFO']._serialized_start=990
  _globals['_MEMMAPINFO']._serialized_end=1033
# @@protoc_insertion_point(module_scope)
