/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: data.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "data.pb-c.h"
void   archie__data__init
                     (Archie__Data         *message)
{
  static const Archie__Data init_value = ARCHIE__DATA__INIT;
  *message = init_value;
}
size_t archie__data__get_packed_size
                     (const Archie__Data *message)
{
  assert(message->base.descriptor == &archie__data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t archie__data__pack
                     (const Archie__Data *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &archie__data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t archie__data__pack_to_buffer
                     (const Archie__Data *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &archie__data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Archie__Data *
       archie__data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Archie__Data *)
     protobuf_c_message_unpack (&archie__data__descriptor,
                                allocator, len, data);
}
void   archie__data__free_unpacked
                     (Archie__Data *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &archie__data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   archie__tb_information__init
                     (Archie__TbInformation         *message)
{
  static const Archie__TbInformation init_value = ARCHIE__TB_INFORMATION__INIT;
  *message = init_value;
}
size_t archie__tb_information__get_packed_size
                     (const Archie__TbInformation *message)
{
  assert(message->base.descriptor == &archie__tb_information__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t archie__tb_information__pack
                     (const Archie__TbInformation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &archie__tb_information__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t archie__tb_information__pack_to_buffer
                     (const Archie__TbInformation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &archie__tb_information__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Archie__TbInformation *
       archie__tb_information__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Archie__TbInformation *)
     protobuf_c_message_unpack (&archie__tb_information__descriptor,
                                allocator, len, data);
}
void   archie__tb_information__free_unpacked
                     (Archie__TbInformation *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &archie__tb_information__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   archie__tb_exec_order__init
                     (Archie__TbExecOrder         *message)
{
  static const Archie__TbExecOrder init_value = ARCHIE__TB_EXEC_ORDER__INIT;
  *message = init_value;
}
size_t archie__tb_exec_order__get_packed_size
                     (const Archie__TbExecOrder *message)
{
  assert(message->base.descriptor == &archie__tb_exec_order__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t archie__tb_exec_order__pack
                     (const Archie__TbExecOrder *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &archie__tb_exec_order__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t archie__tb_exec_order__pack_to_buffer
                     (const Archie__TbExecOrder *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &archie__tb_exec_order__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Archie__TbExecOrder *
       archie__tb_exec_order__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Archie__TbExecOrder *)
     protobuf_c_message_unpack (&archie__tb_exec_order__descriptor,
                                allocator, len, data);
}
void   archie__tb_exec_order__free_unpacked
                     (Archie__TbExecOrder *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &archie__tb_exec_order__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   archie__mem_info__init
                     (Archie__MemInfo         *message)
{
  static const Archie__MemInfo init_value = ARCHIE__MEM_INFO__INIT;
  *message = init_value;
}
size_t archie__mem_info__get_packed_size
                     (const Archie__MemInfo *message)
{
  assert(message->base.descriptor == &archie__mem_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t archie__mem_info__pack
                     (const Archie__MemInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &archie__mem_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t archie__mem_info__pack_to_buffer
                     (const Archie__MemInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &archie__mem_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Archie__MemInfo *
       archie__mem_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Archie__MemInfo *)
     protobuf_c_message_unpack (&archie__mem_info__descriptor,
                                allocator, len, data);
}
void   archie__mem_info__free_unpacked
                     (Archie__MemInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &archie__mem_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   archie__mem_dump_info__init
                     (Archie__MemDumpInfo         *message)
{
  static const Archie__MemDumpInfo init_value = ARCHIE__MEM_DUMP_INFO__INIT;
  *message = init_value;
}
size_t archie__mem_dump_info__get_packed_size
                     (const Archie__MemDumpInfo *message)
{
  assert(message->base.descriptor == &archie__mem_dump_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t archie__mem_dump_info__pack
                     (const Archie__MemDumpInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &archie__mem_dump_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t archie__mem_dump_info__pack_to_buffer
                     (const Archie__MemDumpInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &archie__mem_dump_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Archie__MemDumpInfo *
       archie__mem_dump_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Archie__MemDumpInfo *)
     protobuf_c_message_unpack (&archie__mem_dump_info__descriptor,
                                allocator, len, data);
}
void   archie__mem_dump_info__free_unpacked
                     (Archie__MemDumpInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &archie__mem_dump_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   archie__mem_dump__init
                     (Archie__MemDump         *message)
{
  static const Archie__MemDump init_value = ARCHIE__MEM_DUMP__INIT;
  *message = init_value;
}
size_t archie__mem_dump__get_packed_size
                     (const Archie__MemDump *message)
{
  assert(message->base.descriptor == &archie__mem_dump__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t archie__mem_dump__pack
                     (const Archie__MemDump *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &archie__mem_dump__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t archie__mem_dump__pack_to_buffer
                     (const Archie__MemDump *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &archie__mem_dump__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Archie__MemDump *
       archie__mem_dump__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Archie__MemDump *)
     protobuf_c_message_unpack (&archie__mem_dump__descriptor,
                                allocator, len, data);
}
void   archie__mem_dump__free_unpacked
                     (Archie__MemDump *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &archie__mem_dump__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   archie__register_info__init
                     (Archie__RegisterInfo         *message)
{
  static const Archie__RegisterInfo init_value = ARCHIE__REGISTER_INFO__INIT;
  *message = init_value;
}
size_t archie__register_info__get_packed_size
                     (const Archie__RegisterInfo *message)
{
  assert(message->base.descriptor == &archie__register_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t archie__register_info__pack
                     (const Archie__RegisterInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &archie__register_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t archie__register_info__pack_to_buffer
                     (const Archie__RegisterInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &archie__register_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Archie__RegisterInfo *
       archie__register_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Archie__RegisterInfo *)
     protobuf_c_message_unpack (&archie__register_info__descriptor,
                                allocator, len, data);
}
void   archie__register_info__free_unpacked
                     (Archie__RegisterInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &archie__register_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   archie__register_dump__init
                     (Archie__RegisterDump         *message)
{
  static const Archie__RegisterDump init_value = ARCHIE__REGISTER_DUMP__INIT;
  *message = init_value;
}
size_t archie__register_dump__get_packed_size
                     (const Archie__RegisterDump *message)
{
  assert(message->base.descriptor == &archie__register_dump__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t archie__register_dump__pack
                     (const Archie__RegisterDump *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &archie__register_dump__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t archie__register_dump__pack_to_buffer
                     (const Archie__RegisterDump *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &archie__register_dump__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Archie__RegisterDump *
       archie__register_dump__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Archie__RegisterDump *)
     protobuf_c_message_unpack (&archie__register_dump__descriptor,
                                allocator, len, data);
}
void   archie__register_dump__free_unpacked
                     (Archie__RegisterDump *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &archie__register_dump__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   archie__faulted_data__init
                     (Archie__FaultedData         *message)
{
  static const Archie__FaultedData init_value = ARCHIE__FAULTED_DATA__INIT;
  *message = init_value;
}
size_t archie__faulted_data__get_packed_size
                     (const Archie__FaultedData *message)
{
  assert(message->base.descriptor == &archie__faulted_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t archie__faulted_data__pack
                     (const Archie__FaultedData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &archie__faulted_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t archie__faulted_data__pack_to_buffer
                     (const Archie__FaultedData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &archie__faulted_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Archie__FaultedData *
       archie__faulted_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Archie__FaultedData *)
     protobuf_c_message_unpack (&archie__faulted_data__descriptor,
                                allocator, len, data);
}
void   archie__faulted_data__free_unpacked
                     (Archie__FaultedData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &archie__faulted_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor archie__data__field_descriptors[8] =
{
  {
    "end_point",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Archie__Data, end_point),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end_reason",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Archie__Data, end_reason),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tb_informations",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Archie__Data, n_tb_informations),
    offsetof(Archie__Data, tb_informations),
    &archie__tb_information__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tb_exec_orders",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Archie__Data, n_tb_exec_orders),
    offsetof(Archie__Data, tb_exec_orders),
    &archie__tb_exec_order__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mem_infos",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Archie__Data, n_mem_infos),
    offsetof(Archie__Data, mem_infos),
    &archie__mem_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "register_info",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Archie__Data, register_info),
    &archie__register_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "faulted_datas",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Archie__Data, n_faulted_datas),
    offsetof(Archie__Data, faulted_datas),
    &archie__faulted_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mem_dump_infos",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Archie__Data, n_mem_dump_infos),
    offsetof(Archie__Data, mem_dump_infos),
    &archie__mem_dump_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned archie__data__field_indices_by_name[] = {
  0,   /* field[0] = end_point */
  1,   /* field[1] = end_reason */
  6,   /* field[6] = faulted_datas */
  7,   /* field[7] = mem_dump_infos */
  4,   /* field[4] = mem_infos */
  5,   /* field[5] = register_info */
  3,   /* field[3] = tb_exec_orders */
  2,   /* field[2] = tb_informations */
};
static const ProtobufCIntRange archie__data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor archie__data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "archie.Data",
  "Data",
  "Archie__Data",
  "archie",
  sizeof(Archie__Data),
  8,
  archie__data__field_descriptors,
  archie__data__field_indices_by_name,
  1,  archie__data__number_ranges,
  (ProtobufCMessageInit) archie__data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor archie__tb_information__field_descriptors[5] =
{
  {
    "base_address",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Archie__TbInformation, base_address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Archie__TbInformation, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "instruction_count",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Archie__TbInformation, instruction_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_of_exec",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Archie__TbInformation, num_of_exec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "assembler",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Archie__TbInformation, assembler),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned archie__tb_information__field_indices_by_name[] = {
  4,   /* field[4] = assembler */
  0,   /* field[0] = base_address */
  2,   /* field[2] = instruction_count */
  3,   /* field[3] = num_of_exec */
  1,   /* field[1] = size */
};
static const ProtobufCIntRange archie__tb_information__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor archie__tb_information__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "archie.TbInformation",
  "TbInformation",
  "Archie__TbInformation",
  "archie",
  sizeof(Archie__TbInformation),
  5,
  archie__tb_information__field_descriptors,
  archie__tb_information__field_indices_by_name,
  1,  archie__tb_information__number_ranges,
  (ProtobufCMessageInit) archie__tb_information__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor archie__tb_exec_order__field_descriptors[2] =
{
  {
    "tb_base_address",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Archie__TbExecOrder, tb_base_address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Archie__TbExecOrder, pos),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned archie__tb_exec_order__field_indices_by_name[] = {
  1,   /* field[1] = pos */
  0,   /* field[0] = tb_base_address */
};
static const ProtobufCIntRange archie__tb_exec_order__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor archie__tb_exec_order__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "archie.TbExecOrder",
  "TbExecOrder",
  "Archie__TbExecOrder",
  "archie",
  sizeof(Archie__TbExecOrder),
  2,
  archie__tb_exec_order__field_descriptors,
  archie__tb_exec_order__field_indices_by_name,
  1,  archie__tb_exec_order__number_ranges,
  (ProtobufCMessageInit) archie__tb_exec_order__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor archie__mem_info__field_descriptors[5] =
{
  {
    "ins_address",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Archie__MemInfo, ins_address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Archie__MemInfo, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "memmory_address",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Archie__MemInfo, memmory_address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "direction",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Archie__MemInfo, direction),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "counter",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Archie__MemInfo, counter),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned archie__mem_info__field_indices_by_name[] = {
  4,   /* field[4] = counter */
  3,   /* field[3] = direction */
  0,   /* field[0] = ins_address */
  2,   /* field[2] = memmory_address */
  1,   /* field[1] = size */
};
static const ProtobufCIntRange archie__mem_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor archie__mem_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "archie.MemInfo",
  "MemInfo",
  "Archie__MemInfo",
  "archie",
  sizeof(Archie__MemInfo),
  5,
  archie__mem_info__field_descriptors,
  archie__mem_info__field_indices_by_name,
  1,  archie__mem_info__number_ranges,
  (ProtobufCMessageInit) archie__mem_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor archie__mem_dump_info__field_descriptors[3] =
{
  {
    "address",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Archie__MemDumpInfo, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "len",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Archie__MemDumpInfo, len),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dumps",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Archie__MemDumpInfo, n_dumps),
    offsetof(Archie__MemDumpInfo, dumps),
    &archie__mem_dump__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned archie__mem_dump_info__field_indices_by_name[] = {
  0,   /* field[0] = address */
  2,   /* field[2] = dumps */
  1,   /* field[1] = len */
};
static const ProtobufCIntRange archie__mem_dump_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor archie__mem_dump_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "archie.MemDumpInfo",
  "MemDumpInfo",
  "Archie__MemDumpInfo",
  "archie",
  sizeof(Archie__MemDumpInfo),
  3,
  archie__mem_dump_info__field_descriptors,
  archie__mem_dump_info__field_indices_by_name,
  1,  archie__mem_dump_info__number_ranges,
  (ProtobufCMessageInit) archie__mem_dump_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor archie__mem_dump__field_descriptors[1] =
{
  {
    "mem",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Archie__MemDump, mem),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned archie__mem_dump__field_indices_by_name[] = {
  0,   /* field[0] = mem */
};
static const ProtobufCIntRange archie__mem_dump__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor archie__mem_dump__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "archie.MemDump",
  "MemDump",
  "Archie__MemDump",
  "archie",
  sizeof(Archie__MemDump),
  1,
  archie__mem_dump__field_descriptors,
  archie__mem_dump__field_indices_by_name,
  1,  archie__mem_dump__number_ranges,
  (ProtobufCMessageInit) archie__mem_dump__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor archie__register_info__field_descriptors[2] =
{
  {
    "register_dumps",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Archie__RegisterInfo, n_register_dumps),
    offsetof(Archie__RegisterInfo, register_dumps),
    &archie__register_dump__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "arch_type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Archie__RegisterInfo, arch_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned archie__register_info__field_indices_by_name[] = {
  1,   /* field[1] = arch_type */
  0,   /* field[0] = register_dumps */
};
static const ProtobufCIntRange archie__register_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor archie__register_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "archie.RegisterInfo",
  "RegisterInfo",
  "Archie__RegisterInfo",
  "archie",
  sizeof(Archie__RegisterInfo),
  2,
  archie__register_info__field_descriptors,
  archie__register_info__field_indices_by_name,
  1,  archie__register_info__number_ranges,
  (ProtobufCMessageInit) archie__register_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor archie__register_dump__field_descriptors[3] =
{
  {
    "register_values",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Archie__RegisterDump, n_register_values),
    offsetof(Archie__RegisterDump, register_values),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pc",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Archie__RegisterDump, pc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tb_count",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Archie__RegisterDump, tb_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned archie__register_dump__field_indices_by_name[] = {
  1,   /* field[1] = pc */
  0,   /* field[0] = register_values */
  2,   /* field[2] = tb_count */
};
static const ProtobufCIntRange archie__register_dump__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor archie__register_dump__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "archie.RegisterDump",
  "RegisterDump",
  "Archie__RegisterDump",
  "archie",
  sizeof(Archie__RegisterDump),
  3,
  archie__register_dump__field_descriptors,
  archie__register_dump__field_indices_by_name,
  1,  archie__register_dump__number_ranges,
  (ProtobufCMessageInit) archie__register_dump__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor archie__faulted_data__field_descriptors[2] =
{
  {
    "trigger_address",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Archie__FaultedData, trigger_address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "assembler",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Archie__FaultedData, assembler),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned archie__faulted_data__field_indices_by_name[] = {
  1,   /* field[1] = assembler */
  0,   /* field[0] = trigger_address */
};
static const ProtobufCIntRange archie__faulted_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor archie__faulted_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "archie.FaultedData",
  "FaultedData",
  "Archie__FaultedData",
  "archie",
  sizeof(Archie__FaultedData),
  2,
  archie__faulted_data__field_descriptors,
  archie__faulted_data__field_indices_by_name,
  1,  archie__faulted_data__number_ranges,
  (ProtobufCMessageInit) archie__faulted_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
