/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: control.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "control.pb-c.h"
void   archie__config__init
                     (Archie__Config         *message)
{
  static const Archie__Config init_value = ARCHIE__CONFIG__INIT;
  *message = init_value;
}
size_t archie__config__get_packed_size
                     (const Archie__Config *message)
{
  assert(message->base.descriptor == &archie__config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t archie__config__pack
                     (const Archie__Config *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &archie__config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t archie__config__pack_to_buffer
                     (const Archie__Config *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &archie__config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Archie__Config *
       archie__config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Archie__Config *)
     protobuf_c_message_unpack (&archie__config__descriptor,
                                allocator, len, data);
}
void   archie__config__free_unpacked
                     (Archie__Config *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &archie__config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   archie__end__init
                     (Archie__End         *message)
{
  static const Archie__End init_value = ARCHIE__END__INIT;
  *message = init_value;
}
size_t archie__end__get_packed_size
                     (const Archie__End *message)
{
  assert(message->base.descriptor == &archie__end__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t archie__end__pack
                     (const Archie__End *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &archie__end__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t archie__end__pack_to_buffer
                     (const Archie__End *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &archie__end__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Archie__End *
       archie__end__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Archie__End *)
     protobuf_c_message_unpack (&archie__end__descriptor,
                                allocator, len, data);
}
void   archie__end__free_unpacked
                     (Archie__End *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &archie__end__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   archie__memory__region__init
                     (Archie__MemoryRegion         *message)
{
  static const Archie__MemoryRegion init_value = ARCHIE__MEMORY__REGION__INIT;
  *message = init_value;
}
size_t archie__memory__region__get_packed_size
                     (const Archie__MemoryRegion *message)
{
  assert(message->base.descriptor == &archie__memory__region__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t archie__memory__region__pack
                     (const Archie__MemoryRegion *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &archie__memory__region__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t archie__memory__region__pack_to_buffer
                     (const Archie__MemoryRegion *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &archie__memory__region__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Archie__MemoryRegion *
       archie__memory__region__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Archie__MemoryRegion *)
     protobuf_c_message_unpack (&archie__memory__region__descriptor,
                                allocator, len, data);
}
void   archie__memory__region__free_unpacked
                     (Archie__MemoryRegion *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &archie__memory__region__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor archie__config__field_descriptors[17] =
{
  {
    "max_duration",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Archie__Config, max_duration),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_faults",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Archie__Config, num_faults),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tb_exec_list",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Archie__Config, tb_exec_list),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tb_info",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Archie__Config, tb_info),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mem_info",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Archie__Config, mem_info),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start_address",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Archie__Config, start_address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start_counter",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Archie__Config, start_counter),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end_list",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Archie__Config, n_end_list),
    offsetof(Archie__Config, end_list),
    &archie__end__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tb_exec_list_ring_buffer",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Archie__Config, tb_exec_list_ring_buffer),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_memregions",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Archie__Config, num_memregions),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "memorydump",
    11,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Archie__Config, n_memorydump),
    offsetof(Archie__Config, memorydump),
    &archie__memory__region__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "exists_tb_exec_list",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Archie__Config, exists_tb_exec_list),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "exists_tb_info",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Archie__Config, exists_tb_info),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "exists_start",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Archie__Config, exists_start),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "exists_end",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Archie__Config, exists_end),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "exists_memory_dump",
    16,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Archie__Config, exists_memory_dump),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "exists_ring_buffer",
    17,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Archie__Config, exists_ring_buffer),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned archie__config__field_indices_by_name[] = {
  7,   /* field[7] = end_list */
  14,   /* field[14] = exists_end */
  15,   /* field[15] = exists_memory_dump */
  16,   /* field[16] = exists_ring_buffer */
  13,   /* field[13] = exists_start */
  11,   /* field[11] = exists_tb_exec_list */
  12,   /* field[12] = exists_tb_info */
  0,   /* field[0] = max_duration */
  4,   /* field[4] = mem_info */
  10,   /* field[10] = memorydump */
  1,   /* field[1] = num_faults */
  9,   /* field[9] = num_memregions */
  5,   /* field[5] = start_address */
  6,   /* field[6] = start_counter */
  2,   /* field[2] = tb_exec_list */
  8,   /* field[8] = tb_exec_list_ring_buffer */
  3,   /* field[3] = tb_info */
};
static const ProtobufCIntRange archie__config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 17 }
};
const ProtobufCMessageDescriptor archie__config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "archie.Config",
  "Config",
  "Archie__Config",
  "archie",
  sizeof(Archie__Config),
  17,
  archie__config__field_descriptors,
  archie__config__field_indices_by_name,
  1,  archie__config__number_ranges,
  (ProtobufCMessageInit) archie__config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor archie__end__field_descriptors[2] =
{
  {
    "address",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Archie__End, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "counter",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Archie__End, counter),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned archie__end__field_indices_by_name[] = {
  0,   /* field[0] = address */
  1,   /* field[1] = counter */
};
static const ProtobufCIntRange archie__end__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor archie__end__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "archie.End",
  "End",
  "Archie__End",
  "archie",
  sizeof(Archie__End),
  2,
  archie__end__field_descriptors,
  archie__end__field_indices_by_name,
  1,  archie__end__number_ranges,
  (ProtobufCMessageInit) archie__end__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor archie__memory__region__field_descriptors[2] =
{
  {
    "address",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Archie__MemoryRegion, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "length",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Archie__MemoryRegion, length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned archie__memory__region__field_indices_by_name[] = {
  0,   /* field[0] = address */
  1,   /* field[1] = length */
};
static const ProtobufCIntRange archie__memory__region__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor archie__memory__region__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "archie.Memory_Region",
  "MemoryRegion",
  "Archie__MemoryRegion",
  "archie",
  sizeof(Archie__MemoryRegion),
  2,
  archie__memory__region__field_descriptors,
  archie__memory__region__field_indices_by_name,
  1,  archie__memory__region__number_ranges,
  (ProtobufCMessageInit) archie__memory__region__init,
  NULL,NULL,NULL    /* reserved[123] */
};
