/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: fault.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "fault.pb-c.h"
void   archie__fault__init
                     (Archie__Fault         *message)
{
  static const Archie__Fault init_value = ARCHIE__FAULT__INIT;
  *message = init_value;
}
size_t archie__fault__get_packed_size
                     (const Archie__Fault *message)
{
  assert(message->base.descriptor == &archie__fault__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t archie__fault__pack
                     (const Archie__Fault *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &archie__fault__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t archie__fault__pack_to_buffer
                     (const Archie__Fault *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &archie__fault__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Archie__Fault *
       archie__fault__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Archie__Fault *)
     protobuf_c_message_unpack (&archie__fault__descriptor,
                                allocator, len, data);
}
void   archie__fault__free_unpacked
                     (Archie__Fault *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &archie__fault__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   archie__fault__pack__init
                     (Archie__FaultPack         *message)
{
  static const Archie__FaultPack init_value = ARCHIE__FAULT__PACK__INIT;
  *message = init_value;
}
size_t archie__fault__pack__get_packed_size
                     (const Archie__FaultPack *message)
{
  assert(message->base.descriptor == &archie__fault__pack__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t archie__fault__pack__pack
                     (const Archie__FaultPack *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &archie__fault__pack__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t archie__fault__pack__pack_to_buffer
                     (const Archie__FaultPack *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &archie__fault__pack__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Archie__FaultPack *
       archie__fault__pack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Archie__FaultPack *)
     protobuf_c_message_unpack (&archie__fault__pack__descriptor,
                                allocator, len, data);
}
void   archie__fault__pack__free_unpacked
                     (Archie__FaultPack *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &archie__fault__pack__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor archie__fault__field_descriptors[9] =
{
  {
    "address",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Archie__Fault, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Archie__Fault, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "model",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Archie__Fault, model),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lifespan",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Archie__Fault, lifespan),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "trigger_address",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Archie__Fault, trigger_address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "trigger_hitcounter",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Archie__Fault, trigger_hitcounter),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mask_upper",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Archie__Fault, mask_upper),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mask_lower",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Archie__Fault, mask_lower),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_bytes",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Archie__Fault, num_bytes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned archie__fault__field_indices_by_name[] = {
  0,   /* field[0] = address */
  3,   /* field[3] = lifespan */
  7,   /* field[7] = mask_lower */
  6,   /* field[6] = mask_upper */
  2,   /* field[2] = model */
  8,   /* field[8] = num_bytes */
  4,   /* field[4] = trigger_address */
  5,   /* field[5] = trigger_hitcounter */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange archie__fault__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor archie__fault__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "archie.Fault",
  "Fault",
  "Archie__Fault",
  "archie",
  sizeof(Archie__Fault),
  9,
  archie__fault__field_descriptors,
  archie__fault__field_indices_by_name,
  1,  archie__fault__number_ranges,
  (ProtobufCMessageInit) archie__fault__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor archie__fault__pack__field_descriptors[1] =
{
  {
    "faults",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Archie__FaultPack, n_faults),
    offsetof(Archie__FaultPack, faults),
    &archie__fault__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned archie__fault__pack__field_indices_by_name[] = {
  0,   /* field[0] = faults */
};
static const ProtobufCIntRange archie__fault__pack__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor archie__fault__pack__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "archie.Fault_Pack",
  "FaultPack",
  "Archie__FaultPack",
  "archie",
  sizeof(Archie__FaultPack),
  1,
  archie__fault__pack__field_descriptors,
  archie__fault__pack__field_indices_by_name,
  1,  archie__fault__pack__number_ranges,
  (ProtobufCMessageInit) archie__fault__pack__init,
  NULL,NULL,NULL    /* reserved[123] */
};
