name: lint

on:
  pull_request:
    branches: [ master ]
  push:

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install flake8
      - run: >
            flake8 --exclude .git,__pycache__,"*_pb2.py","*_pb2.pyi"
            --max-line-length=88
            --ignore=E203,E266,E501,W503

  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install black
      - run: |
          black --version
          black --check --diff *.py analysis/*.py --force-exclude *_pb2.py *_pb2.pyi
